name: ai-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - python==3.12
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - python-graphviz
  - transformers==4.49.0
  - jupyter
  - pip:
    - tensorflow_hub
    - tensorflow==2.19.0
    - tensorflow_text==2.19.0
    - datasets
    - sentence-transformers
    - accelerate
    - torch==2.6.0